### ISSUE TITLE
Copy and document fully the FLORIS power/AEP computation components

### ISSUE THREAD

**Issue by cfrontin** [WISDEM/Ard#5]

**Comment by rafmudaf** [comment]
I can configure a basic documentation site so that we can have a place to hold docs. It doesn't have to be perfect (or even very good) to start, but I find it helpful to have somewhere to put things and then eventually we can go back and refine it.

If you're ok with that, I'll start putting together a Jupyter Book site that follows the [diataxis](https://diataxis.fr) framework (Tutorial, How To Guide, Explanation, Reference). This is how I initially structure the [FLORIS docs](https://nrel.github.io/floris/) (though it's deviated as needed) and [FPM](https://fpm.fortran-lang.org) is another good example.

**Comment by cfrontin** [comment]
that'd be great! my only strong preferences here is that a lot of codes/their docs have fallen off on the reference quadrant and I'd like to be strong on that one. but this seems like a great framework to succeed in!
